---
version: '2.3'

services:
  train:
    image: gcr.io/kinsol-generic/yolov7:${TAG:-dev}
    build:
      context: .
      dockerfile: ./Dockerfile
    runtime: nvidia
    volumes:
      - .:/yolo
      - /mnt/NAS/Public/datasets/speedco_dataset:/yolo/speedco_dataset
      - /etc/passwd:/etc/passwd:ro
      - /etc/groups:/etc/groups:ro
    user: 1007:1007
    command: 
      - bash
    shm_size: 64g
    working_dir: /yolo
